packaging_format = 2

id = "focalboard"
name = "Focalboard"
description.en = "Kanban project management software"
description.fr = "Logiciel de gestion de projet Kanban"

version = "7.9.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.focalboard.com/"
admindoc = "https://www.focalboard.com/guide/admin/"
userdoc = "https://www.focalboard.com/guide/user/"
code = "https://github.com/mattermost/focalboard"

[integration]
yunohost = ">= 11.1.13"
architectures = ["amd64"]
multi_instance = false
ldap =  false
sso = false
disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, Focalboard will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Focalboard sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
